language: node_js
node_js:
- '10'
- '11'
- '12'
- '13'
- lts/*
- node
deploy:
  provider: npm
  email: nessthehero@gmail.com
  api_key:
    secure: LQGxnAgE8XfvyV5zQYDbGqANFEnJNLejrZvQi3DymQEJFMsNQD6uBDItf61Bm4DbYRB4sB7Z5rvB6VCf6rALOIqSHNRBIbBEacd9el+q9zRWD1k57vb3xl/r7gidzH7/TPkoXKrX+6KgWgutWFLg9CE+GrbLrCPyZKXzytmAc4o=
  on:
    tags: true
    repo: BarkleyREI/brei-assemble-structure
  skip_cleanup: 'true'
